### ISSUE TITLE
Installation failure on OS X

### ISSUE THREAD

**Issue by swestcott** [japulickal/Tracker#1]
I'm running Chrome 5.0.375.99 on Snow Leopard. I get the following error when clicking the "Install" button,

"Extension Installation Failure

Path names must not be absolute or contain '..'."

**Comment by japulickal** [comment]
Simon I have just corrected this issue and published . Can you give it a try

https://chrome.google.com/extensions/detail/ghegdpnjdllbgoohclhlcbgibbbamhpb

**Comment by swestcott** [comment]
Perfect :)
