### ISSUE TITLE
Tracker opens two tabs when I click on it

### ISSUE THREAD

**Issue by rickyclarkson** [japulickal/Tracker#4]
I set the RSS feed to a Trac report, the number of open issues shows properly, but then when I click on the Tracker icon two tabs are opened, both of which are populated by the report.

**Comment by japulickal** [comment]
Can you send me your browser version please. That will be help full for me to debug

**Comment by rickyclarkson** [comment]
6.0.472.62 (OS X Snow Leopard)

**Comment by rickyclarkson** [comment]
A restart of Chrome seemed to fix this.  I'm still on the same version.
