### ISSUE TITLE
Clicking the icon opens more than one tab

### ISSUE THREAD

**Issue by phenome** [japulickal/Tracker#5]
OK... It opened two tabs, and I have two 'open' tickets, but both tabs showed the same report screen, instead of each ticket pages.

I'd personally like it to open just one tab with the report screen. But even if the idea is to open #tickets number of tabs, each showing each ticket... It's still flawed.

**Comment by phenome** [comment]
Should be merged with issue #4...

Using Chrome 9.0.587.0 dev on Windows.

**Comment by phenome** [comment]
And, as per issue #4, a restart of chrome seemed to fix it.

It's best to leave this open. Should be an easy fix.

**Comment by japulickal** [comment]
Fixed the bug at Version: 1.0.3.

Thank you reporting the  bug.
